# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Serto' do
  pod 'AppCenterReactNativeShared', '~> 1.13.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Serto

  

  platform :ios, '9.0'

  target 'SertoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Serto-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Serto-tvOS

  target 'Serto-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
