# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Serto' do
  pod 'AppCenterReactNativeShared', '~> 1.13.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Serto

  platform :ios, '9.0'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # Needed for debugging
    'RCTAnimation', # Needed for FlatList and animations running on native UI thread
    # Add any other subspecs you want to use in your project
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  # Packages
  pod 'SentryReactNative', :path => '../node_modules/react-native-sentry/SentryReactNative.podspec'
  pod 'RNAnalytics', :path => '../node_modules/@segment/analytics-react-native'
  pod 'react-native-camera', :path => '../node_modules/react-native-camera'
  pod 'RNScreens', :path => '../node_modules/react-native-screens'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RNLocalize', :path => '../node_modules/react-native-localize'

  target 'SertoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

