export const Screens = {
  Home: { screen: 'Home', title: 'Serto' },
  Settings: { screen: 'Settings', title: 'Settings' },
  Codepush: { screen: 'Codepush', title: 'Codepush' },
  Signer: { screen: 'Signer', title: 'Signer' },
  Config: { screen: 'Config', title: 'Config' },
  Crash: { screen: 'Crash', title: 'Crash Reporting' },
  Scanner: { screen: 'Scanner', title: 'Scanner' },
  MessageProcess: { screen: 'MessageProcess', title: 'Message Process' },
  Messages: { screen: 'Messages', title: 'Messages' },
  Connections: { screen: 'Connections', title: 'Connections' },
  DidViewer: { screen: 'DidViewer', title: 'DidViewer' },
  ModalDemo: { screen: 'ModalDemo', title: 'Modal Demo' },
  IdentitySelectModal: { screen: 'IdentitySelectModal', title: 'Identities' },
  Claim: { screen: 'Claim', title: 'Claim Demo' },
  DisclosureRequest: {
    screen: 'DisclosureRequest',
    title: 'Disclosure Request',
  },
  Request: {
    screen: 'Request',
    title: 'Request',
  },
  Credentials: { screen: 'Credentials', title: 'Credentials' },
  Onboarding: { screen: 'Onboarding', title: 'Onboarding' },
  Restore: { screen: 'Restore', title: 'Restore' },
  Intro: { screen: 'Intro', title: 'Intro' },
  CreatingWallet: { screen: 'CreatingWallet', title: 'Creating Wallet' },
  IdentityCheck: { screen: 'IdentityCheck', title: 'Identity Check' },
  Credential: { screen: 'Credential', title: 'Credential' },
  Activity: { screen: 'Activity', title: 'Activity' },
  Explore: { screen: 'Explore', title: 'Explore' },
  Profile: { screen: 'Profile', title: 'Profile' },
}
