# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

desc "Build and sign Android APK"
lane :assemble_android_build do
  production_properties = {
    "android.injected.signing.store.file" => "release-key.keystore",
    "android.injected.signing.store.password" => ENV['ANDROID_STORE_PASSWORD'],
    "android.injected.signing.key.alias" => ENV['ANDROID_KEY_ALIAS'],
    "android.injected.signing.key.password" => ENV['ANDROID_STORE_PASSWORD']
  }

  gradle(task: "assemble", build_type: "Release", print_command: false, properties: production_properties)
end

desc "Build and deploy APK to Google Play"
lane :deploy_android do
  # Can be changed to another track (e.g. 'beta')
  upload_to_play_store(track: 'internal')
end

desc "Clean project"
lane :clean_android do
  gradle(
    task: "clean"
  ) 
end

# Un-comment to run dummy build. Do not commit un-commented code.

# desc "Build Android app (dummy)"
# lane :assemble_android_dummy_build do
#   dummy_properties = {
#     "android.injected.signing.store.file" => "app/dummy-release-key.key",
#     "android.injected.signing.store.password" => "sertodummy",
#     "android.injected.signing.key.alias" => "dummy-serto-release-key",
#     "android.injected.signing.key.password" => "sertodummy"
#   }

#   gradle(task: "assemble", build_type: "Release", properties: dummy_properties)
# end
